kind: Kustomization

namespace: frontend-ns 

resources:
  - namespace.yaml 
  - rolebinding.yaml
  - deployment.yaml
  - service.yaml 
  - route.yaml
  - serviceentry.yaml
  - virtualservice.yaml
  - test-pod.yaml