apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: frontend-ns
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sleep", "3600"]

  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault