apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: product-api-routing
  namespace: frontend-ns
spec:
  hosts:
    - product-api.internal #service entry fqdn
  http:
    - match:
        - headers:
            x-env-target:
              exact: dev
      route:
        - destination:
            host: backend.dev.svc.cluster.local
            port:
              number: 8080
    - match:
        - headers:
            x-env-target:
              exact: prod
      route:
        - destination:
            host: backend.prod.svc.cluster.local
            port:
              number: 8080
    - match:
        - headers:
            x-env-target:
              exact: qa
      route:
        - destination:
            host: backend.qa.svc.cluster.local
            port:
              number: 8080
