apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: openshift-gitops
spec:
  destination:
    namespace: frontend-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: frontend
    repoURL: https://github.com/bugbiteme/ossm-header-routing.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
