apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa
  namespace: openshift-gitops
spec:
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  project: default
  source:
    path: backend/overlays/qa
    repoURL: https://github.com/bugbiteme/ossm-header-routing.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
