apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
    version: v1
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: app
    app.openshift.io/runtime: quarkus
  name: backend-v1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
        deployment: backend
        version: "v1"
    spec:
      containers:
      - env:
        - name: SERVICE_LOCAL
          value: prod
        - name: SERVICE_REMOTE
          value: service-a
        image: quay.io/llevy/service-b:v1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        name: backend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30